name: Dungeonator
main: com.aranai.dungeonator.Dungeonator
version: 0.0.4-P2
author: Timberjaw
load: startup
commands:
  edit:
    description: Use an edit command
    usage: /<command> <task> <args ...>